### PR TITLE
fix: bullet crash on Wechat iOS

### PR DESCRIPTION
**Pull request by PPpro**
Re: https://github.com/cocos/3d-tasks/issues/16827

### Changelog

* fix bullet crash on Wechat iOS

-------

### Continuous Integration

This pull request:

* [x] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by PPpro** [comment]
I've tested on Wechat iOS, web and windows platforms @minggo

**Comment by minggo** [comment]
Please test more platforms to make sure it works for all platforms.

**Review by lealzhan — APPROVED** [review]

**Comment by PPpro** [comment]
@cocos-robot run test cases

**Comment by PPpro** [comment]
I've tested Android and Mac platforms, 

I'll use auto PR test to test the rest platforms @minggo

**Comment by PPpro** [comment]
the action is waiting here https://github.com/cocos/cocos-engine/actions/runs/5209805306

**Review by minggo — APPROVED** [review]

**Comment by PPpro** [comment]
auto test issues on windows and android is the matter of Text alignment.

**Comment by sushanhong** [comment]
@cocos-robot run test cases

**Pull request merged**
