### PR TITLE
Fixed SpriteRender Atlas Render Bug

### PR DESCRIPTION
**Pull request by vikingsc2007**
https://forum.cocos.org/t/topic/155791/2

### CODE REVIEW

**Comment by zhitaocai** [comment]
Why is this PR closed? I merged this PR and tested it myself, and it does solve the problem.

**Comment by minggo** [comment]
It is closed automatically by github when the branch is deleted. We will take a look of this PR.

**Comment by zhitaocai** [comment]
Here is a demo that can reproduce the problem.

https://forum.cocos.org/t/topic/155791/7

**Comment by qiuguohua** [comment]
Recommit a PR on branch 3.8.5.

**Pull request closed without merging**
