### PR TITLE
Disable auto lint when save

### PR DESCRIPTION
**Pull request by shrinktofit**
Re: cocos-creator/3d-tasks#

Changelog:
 * We should do this manually

### CODE REVIEW

**Comment by shrinktofit** [comment]
@pandamicro  Could this be safely merged in favor of https://github.com/cocos-creator/engine/pull/7964 ?

**Comment by pandamicro** [comment]
Yes, I think so, our developers can enable auto save in their local settings of VSCode

**Comment by SantyWang** [comment]
It seems that most people prefer auto-fix, Let's give it a little more time

**Comment by YunHsiao** [comment]
The only way I see this could become reasonable is after we build an auto-fix robot that submits fix PRs automatically after every merge operation. Until then I suggest keeping this as-is.

**Pull request closed without merging**
