### PR TITLE
Compatible with old webgl RC

### PR DESCRIPTION
**Pull request by PPpro**
re: https://github.com/cocos-creator/3d-tasks/issues/3986

changLog:
- compatibale with experimental-webgl, webkit-3d and moz-webgl rendering context

sync from  pr https://github.com/cocos-creator/engine/pull/3050

### CODE REVIEW

**Comment by pandamicro** [comment]
I don't think it's necessary, all modern browsers have already supported standard webgl

**Comment by PPpro** [comment]
there are still some users who use creator in native webview project，
maybe standard webgl is not supported in these webviews.

in this situation, i think it's necessary~

**Comment by pandamicro** [comment]
> maybe standard webgl is not supported in these webviews.

I need a confirmed information, not a guess. Which platform ?

**Comment by PPpro** [comment]
met a user running web-mobile on webkit provided by QT，  
the standard webgl is not supported  

the project focuses on the education sector  

so far all I know is this platform


seems that it's a rarely used case

**Comment by pandamicro** [comment]
> running web-mobile on webkit provided by QT，

I think it's their business to upgrade the QT webkit version, so I'm gonna refuse this PR and close the issue

**Pull request closed without merging**
