### PR TITLE
add the support to upload subregions from buffers to texture

### PR DESCRIPTION
**Pull request by yiwenxue**
Re: https://github.com/cocos/3d-tasks/issues/11268

### Changelog

* add the support to upload subregions from buffers to texture.

-------

### Continuous Integration

This pull request:

* [x] needs automatic test cases check // Manual trigger with `@cocos-robot run test cases` afterward

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by yiwenxue** [comment]
@cocos-robot run test cases

**Comment by yiwenxue** [comment]
@cocos-robot run test cases

**Comment by yiwenxue** [comment]
@cocos-robot run test cases

**Comment by suqionglian** [comment]
@cocos-robot run test cases

**Comment by star-e** [comment]
@cocos-robot run test cases

**Comment by yiwenxue** [comment]
@cocos-robot run test cases

**Review by star-e — APPROVED** [review]

**Pull request merged**
