### PR TITLE
RenderPipeline moved to legacy-pipeline

### PR DESCRIPTION
**Pull request by star-e**
Move `RenderPipeline` to the `legacy-pipeline` module.
Decouple `custom-pipeline` with rest of the engine.

### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check
 
This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

## Greptile Summary

Refactored and streamlined the rendering pipeline setup and management in the Cocos engine.

- **New Utilities for Layout Graphs**: Added `cocos/rendering/custom/layout-graph-editor.ts` for managing and printing layout graphs.
- **Simplified Layout Graph Utilities**: `cocos/rendering/custom/layout-graph-utils.ts` reduced in size by removing redundant functions and imports.
- **Enhanced Custom Pipeline Exports**: Updated `editor/exports/custom-pipeline.ts` to include `layout-graph-editor`.
- **Refactored Pipeline Initialization**: `cocos/root.jsb.ts` and `cocos/root.ts` simplified `setRenderPipeline` method.
- **Removed Unused Components**: `cocos/rendering/legacy/index.jsb.ts` and `cocos/rendering/legacy/index.ts` removed `loadRenderPipeline` and associated imports.

### CODE REVIEW

**Comment by star-e** [comment]
@cocos-robot run test cases

**Comment by star-e** [comment]
image

**Comment by star-e** [comment]
@cocos-robot run test cases

**Comment by star-e** [comment]
@cocos-robot run test cases

**Review by minggo — APPROVED** [review]

**Pull request merged**
