### PR TITLE
Resolve uninitialized uniform for v3.0.1

### PR DESCRIPTION
**Pull request by troublemaker52025**
Re: cocos-creator/3d-tasks#

Changelog:
 *

### CODE REVIEW

**Comment by troublemaker52025** [comment]
https://github.com/cocos-creator/engine/pull/8245

**Comment by troublemaker52025** [comment]
https://github.com/cocos-creator/engine/pull/8260

**Comment by troublemaker52025** [comment]
Submit to version 3.0.1 for fix

**Comment by troublemaker52025** [comment]
https://github.com/cocos-creator/3d-tasks/issues/6174

**Comment by troublemaker52025** [comment]
about native engine： https://github.com/cocos-creator/engine-native/pull/3269

**Comment by troublemaker52025** [comment]
https://github.com/cocos-creator/3d-tasks/issues/6145

**Comment by troublemaker52025** [comment]
https://github.com/cocos-creator/3d-tasks/issues/6123

**Review by caryliu1999 — APPROVED** [review]

**Review by minggo — APPROVED** [review]

**Pull request merged**
