### PR TITLE
Fix MessageQueue deadlock.

### PR DESCRIPTION
**Pull request by bluesky013**
Re: #

### Changelog

* Fix MessageQueue deadlock.

-------

### Continuous Integration

This pull request:

* [x] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by minggo** [comment]
@bluesky013 could you please describe the detail of this issue? Why it has problem with current logic.

**Comment by bluesky013** [comment]
> @bluesky013 could you please describe the detail of this issue? Why it has problem with current logic.

There two shared variables in MessageQueue, the `(atomic_uint)writtenMessageCount` and the `(EventCV)event`.

`writtenMessageCount` is atomic, designed to to pass tail offset of message chunk memory.
`event` combind a `std::mutex` and a `std::condition_variable`, designed to block the consumer thread when MessageQueue is empty.

The issue occurs when the `kickAndWait` is called. The following is a flow chart of a deadlock scenario.
MessageQueue

The execution order is `Consumer::pullMsgs` -> `Main::pushMsgs` -> `Main::signal` -> `Consumer::hasMessage` -> `Consumer::wait`.

`consumer::hasMessage` uses the result of `Consumer::pullMsgs::writtenMessageCount::load` and misses the semaphore signal message. We must ensure the MessageQueue is real empty before thread blocks. So I used a lock to synchronize both `writtenMessageCount` and `event.wait`.

**Comment by minggo** [comment]
Got it.
As using mutex and conditional variable, then does `writtenMessageCount` need to be atomic?

**Comment by bluesky013** [comment]
> Got it. As using mutex and conditional variable, then does `writtenMessageCount` need to be atomic?

`writtenMessageCount` needs to be atomic. It is designed for the lock-free queue. 
* fetch_add in `pushMessages`
* load in `pullMessages`

The mutex is primarily designed for conditional variable.
* wait if the queue does not have new messages.
* signal when main thread kick

`pullMessages` and `executeMessage` can be out of the mutex scope technically. But the current `hasNewMessage` logic uses another `readerContext.newMessageCount`, so I have to put the `pullMessages` in the mutex scope. I'll do some more tests and try to find a better sullosion.

**Comment by minggo** [comment]
Yep, i see the problem, write count may change before wait. It is better to lock as less codes as much. The best is to use lock free design. I am curious how other lock free thread pool work.

**Review by minggo — APPROVED** [review]

**Pull request merged**
