### PR TITLE
Fix removing listener when editbox is closed

### PR DESCRIPTION
**Pull request by qiuguohua**
Re: #

### Changelog

https://forum.cocos.org/t/topic/154931/194?u=king668)

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by minggo** [comment]
Please associate the issue. And please send to v3.8.13 if it is not urgent.

**Comment by qiuguohua** [comment]
> Please associate the issue. And please send to v3.8.13 if it is not urgent.

It's an issue of user feedback.
Is this a small change that could be merged in 3.8.2?

**Comment by minggo** [comment]
> Is this a small change that could be merged in 3.8.2?

Currently, we will only accept urgent fix to make sure v3.8.2 can be released as quickly as possible.

**Comment by qiuguohua** [comment]
OK

**Pull request closed without merging**
