### PR TITLE
fix:engine crash sometime

### PR DESCRIPTION
**Pull request by oahc09**
_queues's element may became dangling pointer, before use cached buffer we call clear. 
(Pass destroy the buffer, but RenderQueue doesn't know)

Re: #

### Changelog

*

-------

### Continuous Integration

This pull request:

* [x] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by oahc09** [comment]
@cocos-robot run test cases

**Comment by minggo** [comment]
How about change to use IntrusivePtr instead of raw pointer.

**Comment by star-e** [comment]
lizhen is currently working on replacing raw pointer with intrusive ptr.

**Comment by oahc09** [comment]
> How about change to use IntrusivePtr instead of raw pointer.

Not suitable, weak ptr is better

**Comment by minggo** [comment]
> lizhen is currently working on replacing raw pointer with intrusive ptr.

Could you please add the link of the PR? Then we may close this one if it is fixed in better way.

**Comment by star-e** [comment]
Here is the pr.
I'm not sure whether lizhen has already fixed this problem.
We need to check
https://github.com/cocos/cocos-engine/pull/12732

**Comment by oahc09** [comment]
> > lizhen is currently working on replacing raw pointer with intrusive ptr.
> 
> Could you please add the link of the PR? Then we may close this one if it is fixed in better way.

I think this pr can be closed.

**Comment by bluesky013** [comment]
> > > lizhen is currently working on replacing raw pointer with intrusive ptr.
> > 
> > 
> > Could you please add the link of the PR? Then we may close this one if it is fixed in better way.
> 
> I think this pr can be closed.

**Comment by bluesky013** [comment]
> Here is the pr. I'm not sure whether lizhen has already fixed this problem. We need to check #12732

#12732 focus on gfx-vulkan and dit not fix this issue.

**Comment by bluesky013** [comment]
I think IntrusivePtr can solve this problem. ```InstancedBuffer*``` here can be a strong reference.

**Pull request closed without merging**
