### PR TITLE
v3.5.1-zqb support asset property preview

### PR DESCRIPTION
**Pull request by arsen2010**
(cherry picked from commit 85769cf8f81459b5ad98ccab4138420009572a32)

[Re: #11698](https://github.com/cocos/3d-tasks/issues/11698)

Changelog:
 *

### CODE REVIEW

**Comment by fish9167** [comment]
@cocos-robot run test cases

**Comment by fish9167** [comment]
@cocos-robot run test cases

**Comment by fish9167** [comment]
@cocos-robot run test cases

**Comment by fish9167** [comment]
@cocos-robot run test cases

**Review by VisualSJ — APPROVED** [review]

**Pull request merged**
