### PR TITLE
Android Build Panel: Add `resizeableActivity`/`maxAspectRatio`

### PR DESCRIPTION
**Pull request by PatriceJiang**
Re: https://github.com/cocos/cocos-engine/issues/15057

This PR replaces the previous unsafe method of using regular expressions to parse and modify the AndroidManifest.xml file in the project. It introduces the use of the xml2js library, which provides a safer and more reliable way to handle XML parsing and manipulation. Additionally, it adds the resizeableActivity attribute for the specified activity.

### Changelog

* Add `xml2js` package to parse AndroidManifest.xml
* Update resizeableActivity attribute
* Add Max Aspect Ratio field

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by minggo** [comment]
@PatriceJiang please attach the screenshot of the build panel.

**Comment by PatriceJiang** [comment]
image

**Review by minggo — APPROVED** [review]

**Comment by PatriceJiang** [comment]
image

Add `Max Aspect Ratio` field

**Comment by minggo** [comment]
Please fix the CI issue.

**Pull request merged**
