### PR TITLE
V3.6.2 fix particle crash

### PR DESCRIPTION
**Pull request by zxx43**
Re: #

### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

issue: https://github.com/cocos/cocos-engine/issues/12893

### CODE REVIEW

**Review by dumganhar — APPROVED** [review]

**Review by dumganhar — APPROVED** [review]

**Comment by dumganhar** [comment]
@cocos-robot run test cases

**Review by SantyWang — APPROVED** [review]

**Comment by zxx43** [comment]
@cocos-robot run test cases

**Comment by wardehuang** [comment]
Not working. The particle cannot show properly. The logcat keep logging 

`JS: [ERROR]: TypeError: Cannot read property 'setUniform' of undefined
    TypeError: Cannot read property 'setUniform' of undefined
        at mJ.updateShaderUniform (src/cocos-js/cc.js:1:1018662)
        at mJ.updateParticles (src/cocos-js/cc.js:1:1018300)
        at c3.update (src/cocos-js/cc.js:1:1072731)
        at eval (eval at qE (src/cocos-js/instantiated-6327ec4c.js:1:454451), <anonymous>:3:65)
`

**Comment by wardehuang** [comment]
Not Working.
After merged these changes, the original particle will not crash any more, however, It will trigger another crash randomly during my gameplay. I cant provide a demo this time.
Below is the crash log:

`
#00 pc 000000000146391c operator= (/buildbot/src/android/ndk-release-r22/toolchain/llvm-project/libcxx/include/string:0) [arm64-v8a]
#01 pc 00000000006011b4 nativevalue_to_se (C:/wegame/client/SanguoIdle/engine/native/cocos/bindings/manual/jsb_conversions_spec.cpp:1475) [arm64-v8a]
#02 pc 00000000008da434 js_assets_Mesh_readAttributeFormatRegistry (C:/wegame/client/SanguoIdle/engine/native/cocos/bindings/auto/jsb_assets_auto.cpp:19889) [arm64-v8a]
#03 pc 0000000000b175bc v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) + 544 [arm64-v8a]
#04 pc 0000000000b16c04 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 652 [arm64-v8a]
#05 pc 0000000000b16394 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 248 [arm64-v8a]
#06 pc 00000000013560e8 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 104 [arm64-v8a]
`

image

**Pull request merged**
