### PR TITLE
[v3.8.5] Fix the bug of tween color property of Sprite.

### PR DESCRIPTION
**Pull request by dumganhar**
Re: #13229

### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by dumganhar** [comment]
ESLint issues are fixed in this PR: https://github.com/cocos/cocos-engine/pull/16948

So I don't fix them here.

**Comment by dumganhar** [comment]
ESLint errors were fixed at https://github.com/cocos/cocos-engine/pull/16948 , so don't fix them here.

**Comment by minggo** [comment]
I was thinking if we need to change Color implementation. Use r, g, b, a instead of _val.

**Comment by dumganhar** [comment]
Yes, it cause some issues that we need to use bit operation in many places.
And Color._var is public and it uses a number instead of 4 numbers which does save some memory. 
So I think it's not the right time to make the change currently.

**Comment by minggo** [comment]
> Yes, but Color._var is public and it uses a number instead of 4 numbers which does save some memory. I think, currently, it's not the right time to make the change.

I see. So i want to create a ticket in forum about it. I want to do it like this because it affects tween system now.

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos/cocos-engine/pull/17021
Close this one.

**Pull request closed without merging**
