### PR TITLE
Fix word wrap for Vietnamese characters

### PR DESCRIPTION
**Pull request by tuan243**
Re: #

Changelog:
 *

### CODE REVIEW

**Comment by SantyWang** [comment]
Thanks for contribution, could you provide a test suite to test this

**Comment by tuan243** [comment]
Hi, can you clarify more about a test suite? How can I provide it?

**Comment by SantyWang** [comment]
> Hi, can you clarify more about a test suite? How can I provide it?

maybe a simple project contained a scene for testing

**Comment by tuan243** [comment]
[test-vietnamese-word-wrap.zip](https://github.com/cocos/cocos-engine/files/8644342/test-vietnamese-word-wrap.zip)
This is a simple project contain some vietnamese string for testing.

**Comment by tuan243** [comment]
Hi, any update?

**Comment by SantyWang** [comment]
Thanks a lot

**Review by SantyWang — APPROVED** [review]

**Comment by ApoorvaDheeraj** [comment]
@holycanvas  @tuan243  - Could you guys please tell me how can i find and add Japanese and Korean word to fix for these lang.   Thanks

**Pull request merged**
