### PR TITLE
3.6 add daily compile CI

### PR DESCRIPTION
**Pull request by PatriceJiang**
Re: #

Changelog:
 *

### CODE REVIEW

**Comment by minggo** [comment]
How to know if meet compile/link error?

**Comment by PatriceJiang** [comment]
> How to know if meet compile/link error?

@fish9167 can help add notification setting.

**Comment by fish9167** [comment]
GitHub Action 脚本（定时任务，手动运行任务）需要放在默认分支才可以

**Comment by minggo** [comment]
@fish9167 please use english in future.
@PatriceJiang so should send to develop branch?  Can not just take effect in v3.6.0?

**Comment by PatriceJiang** [comment]
> so should send to develop branch? Can not just take effect in v3.6.0?

This change is re-commited at https://github.com/cocos/cocos-engine/pull/11061

**Pull request closed without merging**
