### PR TITLE
fixed #3d-tasks/11110: [native] Avoid two implementation of CCObject

### PR DESCRIPTION
**Pull request by dumganhar**
Re: https://github.com/cocos/3d-tasks/issues/11110

### CODE REVIEW

**Comment by dumganhar** [comment]
@cocos-robot run test cases

**Review by novain1102 — APPROVED** [review]

**Review by minggo — APPROVED** [review]

**Review by SantyWang — APPROVED** [review]

**Comment by dumganhar** [comment]
Don't merge, need to do loading performance test first.

**Comment by dumganhar** [comment]
Update performance test result at https://github.com/cocos/cocos-engine/issues/10935
企业微信截图_de0ca987-a807-4eb8-9068-323fa73bf0b3

**Comment by dumganhar** [comment]
@cocos-robot run test cases

**Pull request merged**
