### PR TITLE
fixed #14473: [native] Remove 'Record' macro to avoid conflict.

### LINKED ISSUE #14473: [native] Remove 'Record' macro

### PR DESCRIPTION
**Pull request by dumganhar**
Re: #14473

Reported at https://forum.cocos.org/t/topic/146560

### Changelog

* fixed #14473: [native] Remove 'Record' macro to avoid conflict.

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by dumganhar** [comment]
@cocos-robot run test cases

**Review by minggo — APPROVED** [review]

**Comment by minggo** [comment]
I think it is better to merge it in v3.7.3.

**Comment by star-e** [comment]
Shall we use type alias to define `Record`， so we can differentiate `Record` from plain `std::unordered_map`?

**Review by star-e — APPROVED** [review]

**Comment by dumganhar** [comment]
> Shall we use type alias to define `Record`， so we can differentiate `Record` from plain `std::unordered_map`?

Yep, we could. 
But `Record` is a type in Typescript, I think cpp code should use few Typescript concept as possible.

**Pull request merged**
