### PR TITLE
support friction CCFLOAT

### PR DESCRIPTION
**Pull request by longchuan**
Re: #

### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by minggo** [comment]
Current implementation also supports float though it is strict equal. What's wrong with current implementation?

**Comment by longchuan** [comment]
> Current implementation also supports float though it is strict equal. What's wrong with current implementation?

js' float support many dots,and bullet's float support many dots too.if the friction was bigger than one,the friction could be max,So,the dots should more than six.Limit the float's dot was meaningless setting.The same problem as position's edit.Editor limits the value,but the scene file has no limits.That is conflictive.

**Comment by minggo** [comment]
I don't quite understand the issue. Could you give an example to explain it?

**Comment by longchuan** [comment]
> I don't quite understand the issue. Could you give an example to explain it?

image
look at this,if I set the friction to 3e-15 or 4e-15,there will have diffrent results.But if I set the friction to 1 or 2,the result will not be different.

**Comment by minggo** [comment]
1 and 2 should be different.

**Comment by longchuan** [comment]
> 1 and 2 should be different.

image
reffer to the requirement, the ball could not output.and blocked by the friction
for the output,the rollingFriction should be a large one.
one friction has one result,I got the different results by editing friction.

**Pull request closed without merging**
