### PR TITLE
Fix: use objectId instead of pointer to check for dirty flag in descr…

### PR DESCRIPTION
**Pull request by bluesky013**
…iptorSet.

Re: #

### Changelog

* use objectId instead of pointer to check for dirty flag in descriptorSet.

-------

### Continuous Integration

This pull request:

* [x] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by bluesky013** [comment]
@cocos-robot run test cases

**Review by minggo — APPROVED** [review]

**Comment by minggo** [comment]
Can i know what issue does it fix?

**Review by star-e — APPROVED** [review]

**Comment by star-e** [comment]
When deleting a Texture and then creating a Texture, the returned pointer address might be the same.
If we compare Texture using pointer address, they will be the same, although their contents are different.
This will crash the program.
So we need objectID to distinguish different gfx resources.

**Comment by bluesky013** [comment]
If DescriptorSet holds strong reference of bound resources, the newly created resource pointer would never be the same and pointer can be used to campare.
If it holds weak reference as it does now, DescriptorSet doesn't know bound resource is a valid pointer.

```IntrusivePtr``` can not be used unless that all bound resources are guaranteed to be managed with smart pointer.

**Comment by minggo** [comment]
Got it, thanks.

**Comment by minggo** [comment]
Got it, thanks.

**Comment by bluesky013** [comment]
split from https://github.com/cocos/cocos-engine/pull/12732

**Pull request merged**
