### PR TITLE
remove ia pool.

### PR DESCRIPTION
**Pull request by bluesky013**
Re: #

### Changelog

* remove ia pool.

-------

### Continuous Integration

This pull request:

* [x] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by bluesky013** [comment]
@cocos-robot run test cases

**Review by SantyWang — APPROVED** [review]

**Comment by SantyWang** [comment]
How about the performance? and InputAssembler has its own allocator?

**Comment by SantyWang** [comment]
Please use cocos-benchmark project(BunnyMark scene) to test 2D performance.

**Comment by bluesky013** [comment]
> How about the performance? and InputAssembler has its own allocator?

The Input Assembler is a container for VertexBuffer and IndexBuffer. In the current 2D scenario, they both share the same VB and IB, so there is no need to create an additional IA for different drawInfo.

The Input Assembler should not be coupled with DrawInfo. Set drawInfo interface will be deprecated in 3.9. The correct usage should be as follows:
```cpp
bindInputAssembler()
draw(0, 1)
draw(1, 2)
draw(2, 3)
```

There are no operations that would have a performance impact, and there is no allocator either. The DrawBatch2D simply maintains independent drawInfo.

**Comment by bluesky013** [comment]
> cocos-benchmark

currently under testing.

**Comment by SantyWang** [comment]
>The Input Assembler is a container for VertexBuffer and IndexBuffer. In the current 2D scenario, they both share the same VB and IB, so there is no need to create an additional IA for different drawInfo.
>
>The Input Assembler should not be coupled with DrawInfo. Set drawInfo interface will be deprecated in 3.9. The correct usage should be as follows:
>
>bindInputAssembler()
draw(0, 1)
draw(1, 2)
draw(2, 3)
There are no operations that would have a performance impact, and there is no allocator either. The DrawBatch2D simply maintains independent drawInfo.

I see.

**Comment by bluesky013** [comment]
> Please use cocos-benchmark project(BunnyMark scene) to test 2D performance.

Tested:
Benchmark: BunnyTest （25000）

Env: Adreno (TM) 642L  GLES3.2

f26714d0da1fceef9b01d76cf1c9033

before:
image

after
image

Seems no impact on performance.

**Review by star-e — APPROVED** [review]

**Review by LinYunMo — APPROVED** [review]

**Comment by bluesky013** [comment]
@cocos-robot run test cases

**Pull request merged**
