### PR TITLE
Windows platform handles multiple events at once

### PR DESCRIPTION
**Pull request by qiuguohua**
[issue](https://github.com/cocos/3d-tasks/issues/11391)

### CODE REVIEW

**Comment by minggo** [comment]
Why modify like this?

**Comment by qiuguohua** [comment]
> Why modify like this?

Because events are very fast and rendering is relatively slow, doing so can handle events in a timely manner

**Review by minggo — APPROVED** [review]

**Comment by minggo** [comment]
Any test case to show the difference? Or did you meet any problem?

**Comment by qiuguohua** [comment]
> Any test case to show the difference? Or did you meet any problem?

Not yet, this is what the previous implementation did, and what was missed in the previous adaptation, I will restore it

**Comment by minggo** [comment]
Got it.

**Review by dumganhar — APPROVED** [review]

**Pull request merged**
