### PR TITLE
Fix the issue where setting targetTexture for the Camera component in gameview has no effect.

### PR DESCRIPTION
**Pull request by wuzhiming**
Re: #
https://forum.cocos.org/t/topic/157242/67
### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Review by minggo — APPROVED** [review]

**Comment by minggo** [comment]
Did editor change macro or other things?

**Comment by wuzhiming** [comment]
> Did editor change macro or other things?

when editor is in preview mode it will set `EDITOR_NOT_IN_PREVIEW` to false, the `EDITOR_NOT_IN_PREVIEW` macro is used to distinguish whether the editor is in preview mode.

**Comment by minggo** [comment]
So this component has the problem for a long time?

**Comment by wuzhiming** [comment]
> So this component has the problem for a long time?

It's only occurs in `Preview in Editor`, is works fine in `Preview in Browser`.

**Pull request merged**
