### PR TITLE
fixed #17016: wrong assertion if label is empty and uses BitmapFont

### LINKED ISSUE #17016: 3.8.3 Building Android debug mode may render exceptions
### Cocos Creator version

3.8.3

### System information

Android 14

### Issue description

Since the project was upgraded from 3.8.2 to 3.8.3

When building Android **Debug** mode, there **may be** rendering exceptions (note, it is possible, not guaranteed), and the following error will be reported:

image

In addition, with the same project configuration, when building Android **Release** mode, there will be no rendering exceptions.

After my own investigation, I found that the following places did not perform empty judgment processing, which led to the above problems:

image

At present, I comment out this judgment code, and all rendering exception problems can be solved.

But I haven't found the root cause of the problem. I hope the technical students in the engine team can troubleshoot the positioning problem.

In addition, this problem only occurred after upgrading my project from 3.8.2 to 3.8.3. The same code has no rendering problem in 3.8.2.

### Relevant error log output

_No response_

### Steps to reproduce

---

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by dumganhar**
Re: #17016

Also reported at https://forum.cocos.org/t/topic/160454/17

### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by dumganhar** [comment]
@cocos-robot run test cases

**Comment by dumganhar** [comment]
@cocos-robot run test cases

**Comment by AkshayshettyS** [comment]
Does this fix this issue - [https://forum.cocosengine.org/t/force-updating-label-with-cache-mode-char-gives-error-in-debug-mode/61098](url)

**Comment by dumganhar** [comment]
@AkshayshettyS Yes, it seems to be the same issue.

**Comment by dumganhar** [comment]
@cocos-robot run test cases

**Comment by dumganhar** [comment]
PR test run on windows `PASS`: https://github.com/cocos/cocos-engine/actions/runs/12270410220/job/34235569995

**Review by minggo — APPROVED** [review]

**Pull request merged**
