### PR TITLE
add 'crop' mode to sprite

### PR DESCRIPTION
**Pull request by xuewuli**
Re: cocos-creator/fireball#

add 'crop' mode to sprite

@cocos-creator/engine-admins

### CODE REVIEW

**Comment by pandamicro** [comment]
What's crop mode ? can you be more specific ?

**Comment by xuewuli** [comment]
sorry，it's should be called 'center crop'.
https://developer.android.com/reference/android/widget/ImageView.ScaleType.html

**Comment by pandamicro** [comment]
@nantas what do you think about this feature ?

@xuewuli We have recently refactored the quad data structure in cc.Scale9Sprite, to have better performance and less memory usage, you will need to store the vertices and uvs data into sprite's `_vertices` and `_uvs` data, please refer to the latest version of Scale9Sprite implementation

**Comment by nantas** [comment]
Recently I found this mode useful when studying a project made by old cocos2d-html5, in the old engine you can set a boundingBox to a raw texture to manually 'crop' it during runtime, and it's not possible in Cocos Creator.

So I guess we could use some help here.

**Pull request closed without merging**
