### PR TITLE
[v3.6.0 pipeline] pipeline update

### PR DESCRIPTION
**Pull request by star-e**
pipeline code updated
Changelog:
 * has no impact on current pipeline
 * added executor example
 * changed pipeline present() methods
 * removed unused native executor files
 * add pipelineSceneData to SceneVisitor interface

### CODE REVIEW

**Comment by star-e** [comment]
pipeline代码更新，添加了web executor的示例。移除了暂时不用的native executor。
为SceneVisitor添加 pipelineSceneData接口。
对现有代码没有影响。

**Comment by star-e** [comment]
@cocos-robot run test cases

**Comment by star-e** [comment]
@cocos-robot run test cases

**Comment by star-e** [comment]
@cocos-robot run test cases

**Comment by star-e** [comment]
通过了CI测试，test cases暂时有些问题，还不能用。

**Comment by star-e** [comment]
@cocos-robot run test cases

**Comment by star-e** [comment]
@cocos-robot run test cases

**Comment by star-e** [comment]
@cocos-robot run test cases

**Comment by star-e** [comment]
@cocos-robot run test cases

**Comment by star-e** [comment]
@cocos-robot run test cases

**Comment by star-e** [comment]
通过了ci和test cases

**Review by minggo — APPROVED** [review]

**Pull request merged**
