### PR TITLE
profiler use string_view as argument

### PR DESCRIPTION
**Pull request by PatriceJiang**
Re: #

### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by minggo** [comment]
Why change to use `string_view`?

**Comment by PatriceJiang** [comment]
> Why change to use `string_view`?

Reduce the temporarily allocated string objects and improve the performance of profiler.

**Comment by minggo** [comment]
Do you have any performance test data?

**Comment by PatriceJiang** [comment]
I ran bunny test with 50K nodes on PC, the FPS changed from 20 to 24 after applying string_view.

I profiled 2 function that created 100K temporary string objects per-frame.

**Comment by minggo** [comment]
It seems valuable. Please make sure if `ccstd::pmr::string` can work with std::string_view.

**Comment by PatriceJiang** [comment]
> It seems valuable. Please make sure if `ccstd::pmr::string` can work with std::string_view.

Yes. string_view works fine with pmr::string

**Review by dumganhar — APPROVED** [review]

**Review by minggo — APPROVED** [review]

**Pull request merged**
