### PR TITLE
解决 JSB 中场景切换延迟导致的问题

### PR DESCRIPTION
**Pull request by pandamicro**
> Makes sure these boxes are checked before submitting your PR - thank you!
> - [x] Check that your javascript is following our [style guide](https://github.com/cocos-creator/fireball/blob/dev/.github/CONTRIBUTING.md) and end files with a newline
> - [x] Document new code with comments in source code based on [API Docs](https://github.com/cocos-creator/fireball#api-docs)
> - [x] If your pull request has gone "stale", you should **rebase** your work on top of the latest version of the upstream branch.
> - [x] If your commit history is full of small, unimportant commits (such as "fix pep8" or "update tests"), **squash** your commits down to a few, or one, discreet changesets before submitting a pull request.

Re: cocos-creator/fireball#2223
Re: cocos-creator/fireball#2029

Changes proposed in this pull request:
- 修复 CallbacksInvoker / EventListeners 可能在递归 invoke 过程中覆盖 toRemove 列表的问题
- 解决不延迟切换场景时 start 里禁用的节点会被渲染一帧（runScene 固定延迟一帧）
- 解决延迟切换场景时 persistent node 会闪一下，中间有一帧不会渲染（在真正切换时再 destroy 旧场景）

@cocos-creator/engine-admins

### CODE REVIEW

**Comment by pandamicro** [comment]
@jareguo 如果延迟没有问题，我打算将 web 端 runScene 也做成延迟

**Comment by jareguo** [comment]
没问题做吧

**Comment by pandamicro** [comment]
@jareguo 那把 runScene API 改成下面这样如何：

```
runScene: function (scene, onBeforeLoadScene)

->

runScene: function (scene, onBeforeLoadScene, onLaunched)
```

**Comment by jareguo** [comment]
没问题

**Comment by pandamicro** [comment]
@jareguo 添加了一个 runSceneImmediate API

**Pull request merged**
