### PR TITLE
add builtin pipeline passes

### PR DESCRIPTION
**Pull request by star-e**
Re: #17987

### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by minggo** [comment]
Is it compatible?

**Comment by star-e** [comment]
> Is it compatible?

I will add migration later.

**Comment by minggo** [comment]
Ok. And it is better to create an issue for it.

**Comment by minggo** [comment]
I mean add an issue for `add builtin pipeline passes`, and can add left work in the issue.

**Comment by star-e** [comment]
> I mean add an issue for `add builtin pipeline passes`, and can add left work in the issue.

Issue is created. https://github.com/cocos/cocos-engine/issues/17987

**Review by minggo — APPROVED** [review]

**Pull request merged**
