### PR TITLE
[pipeline] custom pipeline update

### PR DESCRIPTION
**Pull request by star-e**
custom pipeline update

Changelog:
 * stop use IntrusivePtr<gfx::Swapchain>, to fix GfxObject RefCounted compile problem.
 * has no impact on current pipeline

### CODE REVIEW

**Comment by star-e** [comment]
@cocos-robot run test cases

**Comment by star-e** [comment]
@cocos-robot run test cases

**Comment by star-e** [comment]
@cocos-robot run test cases

**Comment by star-e** [comment]
修复了Pipeline因IntrusivePtr\<gfx::Swapchain\>编译不过的问题。
pipeline有代码更新，不会改变现有引擎行为。

**Review by minggo — APPROVED** [review]

**Pull request merged**
