### PR TITLE
Simplify CCClass

### PR DESCRIPTION
**Pull request by jareguo**
Please see below PRs for detailed review records as well as my code description:
- https://github.com/jareguo/engine/pull/7 （Approved by shrinktofit、PP）
- https://github.com/jareguo/engine/pull/8 （Approved by shrinktofit、PP）
- https://github.com/jareguo/engine/pull/9 （Approved by shrinktofit、PP）

### Changelog

Simplify the implementation of CCClass (aka. our Reflection System)

---

After merging this PR, the total time consumed to start the main package of the engine under the editor is 724 ms before optimization and 709 ms after optimization, and the CCClass time consumption is significantly reduced after optimization (CCClass overhead reduced by ~25%). The real machine on the mobile side is yet to be tested, and it is expected to reflect a 20 ~ 50ms reduction.

## Overhead before optimization (partial)
image

## Overhead after optimization (partial)
image

---

Engine web release package, optimizations are focused on the core package, core package reduced by 3.4KB
Engine package size in editor reduced by 10.5 KB

All in all, this PR is on the positive side, both in terms of performance and package size.

TODO: There are currently about 4500 decorators used in the engine. In order to be compatible with \@property usage, it was not possible to optimize very much. If all decorators were defined in the new discrete way, it is expected that they could be optimized significantly. (In V4.0 ?)

-------

### Continuous Integration

This pull request:

* [x] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

-------

### Update

After several months, there have been too many conflicts and I'm too lazy to adjust the code. In theory it supports all versions, but if you need it, cherry-pick it to your branch yourself. The original commits were approved by the official team of the engine, so they should be reliable, but they have not been tested on a large scale. (Of course, as the person who wrote the first line of code for this engine, I am still very confident in the modules that I am responsible for.)

### CODE REVIEW

**Comment by jareguo** [comment]
@shrinktofit This change is new, have a look plz. https://github.com/cocos/cocos-engine/pull/16036/commits/bf32646d78b18e25e020a840aef9c8dbc3782db9

**Comment by shrinktofit** [comment]
LGTM

**Comment by jareguo** [comment]
太多冲突，算了，不提了，爱咋咋地

**Comment by jareguo** [comment]
After several months, there have been too many conflicts and I'm too lazy to adjust the code. In theory it supports all versions, but if you need it, cherry-pick it to your branch yourself. The original commits were approved by the official team of the engine, so they should be reliable, but they have not been tested on a large scale. (Of course, as the person who wrote the first line of code for this engine, I am still very confident in the modules that I am responsible for.)

**Pull request closed without merging**
