### PR TITLE
fix merge lost for 3.0

### PR DESCRIPTION
**Pull request by troublemaker52025**
https://github.com/cocos-creator/3d-tasks/issues/4831
Re: cocos-creator/2d-tasks#

Changes:
 *

### CODE REVIEW

**Comment by troublemaker52025** [comment]
https://github.com/cocos-creator/3d-tasks/issues/4887

**Comment by troublemaker52025** [comment]
https://github.com/cocos-creator/test-cases-3d/pull/336

**Comment by troublemaker52025** [comment]
> 
> 
> [cocos-creator/test-cases-3d#336](https://github.com/cocos-creator/test-cases-3d/pull/336)

旧的场景怎么调都不行，我重新创建了新场景就可以了

**Comment by troublemaker52025** [comment]
https://github.com/cocos-creator/3d-tasks/issues/4831

**Review by pandamicro — APPROVED** [review]

**Pull request merged**
