### PR TITLE
Fix ASTC textures were not displayed correctly on some devices.

### PR DESCRIPTION
**Pull request by yoki0805**
Device: Lenovo Tab M10 FHD Plus
Chip: MediaTek Helio P22T (MT8768T)
Platform: Web-mobile

Unable to display ASTC textures correctly.
Screenshot_2024-10-24-14-31-58-549

After the fix.
Screenshot_2024-10-24-14-34-43-124

Test demo:
[astc-test.zip](https://github.com/user-attachments/files/17502402/astc-test.zip)

Reproduction steps:
1. A specific device is required.
2. Use non-power-of-two ASTC textures.
3. Build the project.
4. Run on the device.

### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by yoki0805** [comment]
This demo only tested cases with Texture_2D & Cube_Map, I wasn't able to test cases with Texture_2D_Array & Texture_3D.
Should the isFullCopy check also be applied to Texture_2D_Array & Texture_3D?

**Comment by star-e** [comment]
Thanks for your pr! We will investigate this issue.

**Comment by yoki0805** [comment]
Have any plan?
@star-e

**Comment by star-e** [comment]
Thanks for your pr. @yoki0805 
We have created an [issue](https://github.com/cocos/cocos-engine/issues/17904) to track this problem. 
The fix in this pr is good, but we have to test it on various platforms.
So it takes some time to incorporate the fix.

**Comment by yoki0805** [comment]
Got it, thank you!

**Pull request closed without merging**
