### PR TITLE
修复加载器的新 bug

### PR DESCRIPTION
**Pull request by pandamicro**
Re: cocos-creator/fireball#5010

Changes proposed in this pull request:
 * Fix clippingNode alphaThreshold property
 * Improve orientation check
 * Fix some raw assets not being set the correct type issue
 * Always use user inputed url as id

> Makes sure these boxes are checked before submitting your PR - thank you!
>
- [x] If your pull request has gone "stale", you should **rebase** your work on top of the latest version of the upstream branch.
- [x] If your commit history is full of small, unimportant commits (such as "fix pep8" or "update tests"), **squash** your commits down to a few, or one, discreet changesets before submitting a pull request.
- To official teams:
  - [x] Check that your javascript is following our [style guide](https://github.com/cocos-creator/fireball/blob/dev/.github/CONTRIBUTING.md) and end files with a newline
  - [x] Document new code with comments in source code based on [API Docs](https://github.com/cocos-creator/fireball#api-docs)
  - [x] Make sure any log information in `cc.log` , `cc.error`, `cc.warn` or `cc.assert` has been moved into `DebugInfos.js` with an ID

@cocos-creator/engine-admins

### CODE REVIEW

**Comment by pandamicro** [comment]
Also for https://github.com/cocos-creator/fireball/issues/4897

**Comment by pandamicro** [comment]
需要等斯杰 Audio 部分的修复一起合并

**Review by jareguo — APPROVED** [review]

**Comment by pandamicro** [comment]
还有个小问题，不确定是否跟 Loader 有关，现在切换场景再切换回去，会报错， scene 的 children 都丢失了

**Review by jareguo — APPROVED** [review]

**Comment by jareguo** [comment]
> 现在切换场景再切换回去，会报错， scene 的 children 都丢失了

我这边运行 example case 似乎没问题

**Comment by pandamicro** [comment]
ok 了，前面的问题都修复了

**Pull request merged**
