### PR TITLE
add raw assets are not cached in the CC_EDITOR for fireball/issues/4158

### PR DESCRIPTION
**Pull request by knoxHuang**
Re: cocos-creator/fireball#4158

Changes proposed in this pull request:
-  添加在 Editor 环境下不缓存 raw assets

@cocos-creator/engine-admins

### CODE REVIEW

**Comment by pandamicro** [comment]
解决 FNT 替换时在编辑器内不会更新的 bug

**Comment by pandamicro** [comment]
LGTM

**Comment by jareguo** [comment]
LGTM

**Comment by knoxHuang** [comment]
如果没问题的话，合并一下 thx

**Pull request merged**
