### PR TITLE
Fix two security issues

### LINKED ISSUE #15002: [Security] Advisory in triage state for a month
Hey, could you please triage https://github.com/cocos/cocos-engine/security/advisories/GHSA-24jj-5hhj-gr8p ?
It's in triage state for about a month.

### PR DESCRIPTION
**Pull request by intrigus-lgtm**
This fixes #15002 and properly fixes #15065 that re-introduced a previous vulnerability.

I have checked this PR against a fork and it worked.

### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [x] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Review by shrinktofit — APPROVED** [review]

**Review by shaoqiangcai — APPROVED** [review]

**Review by minggo — APPROVED** [review]

**Comment by pandamicro** [comment]
@intrigus-lgtm Thank you for the fix

**Comment by shaoqiangcai** [comment]
@intrigus-lgtm 
hello，After merging the code, check 'No Run'
企业微信截图_16872520595500

**Comment by intrigus-lgtm** [comment]
Will look at it soonish.

**Comment by intrigus-lgtm** [comment]
@shaoqiangcai I'm sorry, but what is the problem?
Can you explain it in a bit more detail?

To me it appears that everything is working; I've only opened #15499 to make the action more quiet.

**Comment by shaoqiangcai** [comment]
Our requirement is to check and execute the github action, and there may be interruptions during the execution process. We need to manually trigger the execution again, so we need to check and merge it with manual execution

**Comment by shrinktofit** [comment]
Hi @intrigus-lgtm , we noticed that you removed `marocchino/sticky-pull-request-comment@v2` step in [web-interface-check.yml](https://github.com/cocos/cocos-engine/blob/develop/.github/workflows/web-interface-check.yml). This make us no longer able to post the diff result in PR. What's the solution?

I've added https://github.com/cocos/cocos-engine/pull/15654 back. If you have other suggestions, PRs are welcome.

**Comment by intrigus-lgtm** [comment]
Will have a look at it later today.

**Comment by intrigus-lgtm** [comment]
@shrinktofit can you please show me a PR where the interface check did not work so I can investigate?

Because as far as I tested it, it should just work; I moved the `marocchino/sticky-pull-request-comment@v2` step from https://github.com/cocos/cocos-engine/blob/develop/.github/workflows/web-interface-check.yml to https://github.com/cocos/cocos-engine/blob/develop/.github/workflows/web-interface-check-pr-comment.yml#L23

**Comment by shrinktofit** [comment]
> @shrinktofit can you please show me a PR where the interface check did not work so I can investigate?
> 
> Because as far as I tested it, it should just work; I moved the `marocchino/sticky-pull-request-comment@v2` step from https://github.com/cocos/cocos-engine/blob/develop/.github/workflows/web-interface-check.yml to https://github.com/cocos/cocos-engine/blob/develop/.github/workflows/web-interface-check-pr-comment.yml#L23

@intrigus-lgtm  #15652  . It seems `<Web> Interface check PR comment` actions failed: https://github.com/cocos/cocos-engine/actions

**Comment by intrigus-lgtm** [comment]
This should be fixed once you merge https://github.com/cocos/cocos-engine/pull/15499

**Comment by shrinktofit** [comment]
> This should be fixed once you merge #15499

@intrigus-lgtm  #15499 has been merged, the post comment task still failed: https://github.com/cocos/cocos-engine/actions/runs/5526815786/jobs/10081937362 . It's weird, I sure seen you assigned `number: ${{ github.event.workflow_run.pull_requests[0].number }}`.

**Pull request merged**
