### PR TITLE
Fix label inactivation without calling destroy to release resources

### PR DESCRIPTION
**Pull request by qiuguohua**
Re: #

### Changelog

https://github.com/cocos/cocos-engine/issues/16721

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by minggo** [comment]
I don't understand why it can fix the issue.

**Comment by qiuguohua** [comment]
> I don't understand why it can fix the issue.

super._onpredestroy checks to see if _isOnLoadCalled is included, and calls ondestroy if it is.

Here we rewrite _onpredestroy to determine if it contains _isOnLoadCalled, if so, we go directly to the original logic, if not, we release the resources that have already been applied.

**Comment by minggo** [comment]
Got it, i think it is better to add `override` for the function. And please fix the CI error.

**Review by minggo — APPROVED** [review]

**Comment by huhudage** [comment]
After apply this merge request, if the Label component was destroyed before node's first activation, the Label component will not be removed from node, because super._onPreDestroy() will not be called.

Or is the following a better way?

```
    public _onPreDestroy (): void {
        super._onPreDestroy();

        if (this._isOnLoadCalled) {
            return;
        }
        // If _objFlags does not contain IsOnLoadCalled, it is possible to destroy the ttfSpriteFrame.
        this.destroyTtfSpriteFrame();
    }
```

**Comment by qiuguohua** [comment]
> After apply this merge request, if the Label component was destroyed before node's first activation, the Label component will not be removed from node, because super._onPreDestroy() will not be called.
> 
> Or is the following a better way?
> 
> ```
>     public _onPreDestroy (): void {
>         super._onPreDestroy();
> 
>         if (this._isOnLoadCalled) {
>             return;
>         }
>         // If _objFlags does not contain IsOnLoadCalled, it is possible to destroy the ttfSpriteFrame.
>         this.destroyTtfSpriteFrame();
>     }
> ```

Yes, you're right. I'll fix it later

**Pull request merged**
