### PR TITLE
add protect for event target auto remove

### PR DESCRIPTION
**Pull request by JayceLai**
Re: cocos-creator/3d-tasks#

Changes:
 * add protect for event target auto remove

### CODE REVIEW

**Comment by JayceLai** [comment]
The new way of `Eventify` let component become a wrapper of `CallbacksInvoker`, but it will bug when event target is component`s node.

Because the component is destroyed first.

image

@shrinktofit

**Comment by pandamicro** [comment]
Do you mean component is destroyed first ? And the component is a eventified class, then its callbacks will be destroyed too, then `component.targetOff` is causing problem ?

**Comment by JayceLai** [comment]
Yes.

The old way is add a `CallbackTable` map, but `for in` usage avoid this bug.
image

**Comment by pandamicro** [comment]
I think runtime check is not the best solution.

What we could do instead:

- In `BaseNode._onPreDestroyBase`: clear `eventTargets` (with `targetOff`) before any destroy
- Fundamentally the problem is the `destroy` of Component haven't really cleanup the data, we could add a `destroy` function in `Eventify` for cleanup data.

```
destroy () {
    if (super.destroy) {
        super.destroy();
    }
    this.removeAll();
}
```

Besides, I find that we have potential issues with current `Eventify.removeAll` it should do `_unregisterThisIntoTarget` for all targets registered.

**Pull request closed without merging**
