### PR TITLE
Reduce graph api code

### PR DESCRIPTION
**Pull request by star-e**
Re: #

### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

## Greptile Summary

The pull request renames several graph-related methods across multiple files in the Cocos Engine, focusing on brevity and consistency in naming conventions.

- Renamed 'outEdges' to 'oe', 'outDegree' to 'od', 'inEdges' to 'ie', and 'inDegree' to 'id' in `cocos/rendering/custom/graph.ts`.
- Updated `LayoutGraph` and `LayoutGraphData` classes in `cocos/rendering/custom/layout-graph.ts` with similar method name changes.
- Modified `SubpassGraph`, `ResourceGraph`, and `RenderGraph` classes in `cocos/rendering/custom/render-graph.ts` to use the new shortened method names.
- These changes may impact code readability and require updates in other parts of the codebase that rely on the old method names.

### CODE REVIEW

**Comment by smallmain** [comment]
It's scary...

**Comment by star-e** [comment]
> It's scary...

Yes, it seems scary.

These methods are only used in engine implementation. To reduce code size, methods and members will be shortened aggressively.
Readability will be poor, so we are adding TS Doc comments to improve reasoning.

**Comment by smallmain** [comment]
> > It's scary...
> 
> Yes, it seems scary.
> 
> These methods are only used in engine implementation. To reduce code size, methods and members will be shortened aggressively. Readability will be poor, so we are adding TS Doc comments to improve reasoning.



> > It's scary...
> 
> Yes, it seems scary.
> 
> These methods are only used in engine implementation. To reduce code size, methods and members will be shortened aggressively. Readability will be poor, so we are adding TS Doc comments to improve reasoning.

I looked at the Terser.

​https://terser.org/docs/cli-usage/#cli-mangling-property-names---mangle-props

It seems like there are plenty of options to restrict Mangle to certain properties on certain files, so why go to the trouble of doing it manually? 

Even if you create a 'mangle.json' list file, maintain which files and which properties can be reduced, at least it won't affect development, and is it easier to maintain?

**Comment by star-e** [comment]
> I looked at the Terser.
> 
> ​https://terser.org/docs/cli-usage/#cli-mangling-property-names---mangle-props
> 
> It seems like there are plenty of options to restrict Mangle to certain properties on certain files, so why go to the trouble of doing it manually?
> 
> Even if you create a 'mangle.json' list file, maintain which files and which properties can be reduced, at least it won't affect development, and is it easier to maintain?

We are currently looking at tools that can reduce code. Before we finding a suitable tool, the code size still needs to be reduced.
There are also several other reasons.
1. These codes are generated and the generator is generally easier to maintain. (It also has a list to maintain which properties are reduced.)
2. Introducing another tool might make the building process more error prone. And bugs will be harder to catch.
3. We need to handle TS/C++ inter-operation. In C++ these names are not shortened. The new tool might not able to handle this situation. Currently we are using the generator to solve this problem.

**Comment by smallmain** [comment]
> > I looked at the Terser.
> > ​https://terser.org/docs/cli-usage/#cli-mangling-property-names---mangle-props
> > It seems like there are plenty of options to restrict Mangle to certain properties on certain files, so why go to the trouble of doing it manually?
> > Even if you create a 'mangle.json' list file, maintain which files and which properties can be reduced, at least it won't affect development, and is it easier to maintain?
> 
> We are currently looking at tools that can reduce code. Before we finding a suitable tool, the code size still needs to be reduced. There are also several other reasons.
> 
> 1. These codes are generated and the generator is generally easier to maintain. (It also has a list to maintain which properties are reduced.)
> 2. Introducing another tool might make the building process more error prone. And bugs will be harder to catch.
> 3. We need to handle TS/C++ inter-operation. In C++ these names are not shortened. The new tool might not able to handle this situation. Currently we are using the generator to solve this problem.

That's fine, as long as we don't make the changes manually.

Terser is a popular library and most likely already in the engine's build chain.

I prefer to make improvements in existing tools (including avoiding dealing with TS/C++ glue code) that can be applied to user/engine code more quickly.

**Comment by smallmain** [comment]
> > I looked at the Terser.
> > ​https://terser.org/docs/cli-usage/#cli-mangling-property-names---mangle-props
> > It seems like there are plenty of options to restrict Mangle to certain properties on certain files, so why go to the trouble of doing it manually?
> > Even if you create a 'mangle.json' list file, maintain which files and which properties can be reduced, at least it won't affect development, and is it easier to maintain?
> 
> We are currently looking at tools that can reduce code. Before we finding a suitable tool, the code size still needs to be reduced. There are also several other reasons.
> 
> 1. These codes are generated and the generator is generally easier to maintain. (It also has a list to maintain which properties are reduced.)
> 2. Introducing another tool might make the building process more error prone. And bugs will be harder to catch.
> 3. We need to handle TS/C++ inter-operation. In C++ these names are not shortened. The new tool might not able to handle this situation. Currently we are using the generator to solve this problem.

If it's automatic, I'm even less clear, why commit to the codebase instead of processing it as a build artifact?

**Comment by star-e** [comment]
> If it's automatic, I'm even less clear, why commit to the codebase instead of processing it as a build artifact?

We will add it to build process in the future. Currently we are focusing on other parts of the engine.

**Comment by smallmain** [comment]
> > If it's automatic, I'm even less clear, why commit to the codebase instead of processing it as a build artifact?
> 
> We will add it to build process in the future. Currently we are focusing on other parts of the engine.

Okay, thank you for your answer.

**Review by minggo — APPROVED** [review]

**Comment by dumganhar** [comment]
> Introducing another tool might make the building process more error prone. And bugs will be harder to catch.

I agree this. At this point, we don't have time to test `terser mangle configuration`.
Last week, I played `rollup's terser plugin` , I wrote a `mangle regex`: `properties: \w+\$$` means every property ends with `$` should be reduced.

And I found a potential issue that it generate wrong code.

Something like:


```ts
// __virtual-cc-xxx.js
export("a$") {... }
```

```ts
// cc.js
Size = module.ne; // but here should be `a$`.
```

It's probably a bug in rollup or terser, which generates wrong code in module's chunk file.

In the end, I have to modify the regex to `regex: /^[a-zA-Z_][a-zA-Z0-9_]{3,}\$$/,` to avoid that bug.

**Pull request merged**
