### PR TITLE
Improve EditBox

### PR DESCRIPTION
**Pull request by zilongshanren**
Squashed commit of the following:

commit ad31d2beadceea31732970145238a68a97995b76
Merge: 8e15189 061e6ca
Author: zilongshanren guanghui8827@126.com
Date:   Tue Feb 23 16:51:09 2016 +0800

```
Merge remote-tracking branch 'me/master'
```

commit 8e15189d4a37d7215ffb66d6c08ec0b79cc57a19
Merge: 7c233f0 968480e
Author: zilongshanren guanghui8827@126.com
Date:   Tue Feb 23 16:50:19 2016 +0800

```
Merge remote-tracking branch 'fireball/master'
```

commit 7c233f03db2a78b1ab2c5866520efef04a6c4920
Author: zilongshanren guanghui8827@126.com
Date:   Tue Feb 23 16:47:25 2016 +0800

```
minor fix
```

commit fc89b4f920f979497e5961e48c1c796e18c3aa8e
Author: zilongshanren guanghui8827@126.com
Date:   Tue Feb 23 14:24:43 2016 +0800

```
add editbox reorder functionality
```

commit 6fd1b48199ce351716c43250497e5b192194b1d5
Author: zilongshanren guanghui8827@126.com
Date:   Mon Feb 22 18:21:48 2016 +0800

```
fix label rendering issue on editor
```

commit 2a335cd701ed62c6bc45f8849b4322413cf9acca
Author: zilongshanren guanghui8827@126.com
Date:   Mon Feb 22 16:10:43 2016 +0800

```
add label
```

commit 51180fae14b43bfe2a2e11d618dda7a91b7522f1
Author: zilongshanren guanghui8827@126.com
Date:   Mon Feb 22 14:02:47 2016 +0800

```
refactoring, add EditBoxImpl
```

commit d40cf8839963a98446a3b85f033f352b3325f7ed
Author: zilongshanren guanghui8827@126.com
Date:   Mon Feb 22 11:30:35 2016 +0800

```
add toggle native editbox logic
```

commit 6114905f7222e8a21a8bc32be71f0bef1c4c658e
Author: zilongshanren guanghui8827@126.com
Date:   Fri Feb 19 13:37:34 2016 +0800

```
remove resize and add vertical scrollbar
```

commit 061e6cadf259a2c6ae3b178fb45a747427af8589
Merge: c2a142c 0314e4c
Author: zilongshanren guanghui8827@126.com
Date:   Tue Feb 23 14:25:41 2016 +0800

```
Merge remote-tracking branch 'fireball/master'
```

commit c2a142ce003f2d85d5f161be69f79dd6c0eaa68d
Author: zilongshanren guanghui8827@126.com
Date:   Tue Feb 23 14:24:43 2016 +0800

```
add editbox reorder functionality
```

commit 48f02e97f27847b431c510d60fdf9380b14b650f
Author: zilongshanren guanghui8827@126.com
Date:   Mon Feb 22 18:21:48 2016 +0800

```
fix label rendering issue on editor
```

commit 3b40ce5bd6a9ef8aa6c4f4b7874408e446ecc655
Author: zilongshanren guanghui8827@126.com
Date:   Mon Feb 22 16:10:43 2016 +0800

```
add label
```

commit c304e8f40f9097905023d5bb5206faa6cf20be1a
Author: zilongshanren guanghui8827@126.com
Date:   Mon Feb 22 14:02:47 2016 +0800

```
refactoring, add EditBoxImpl
```

commit 913b52536e9085ec2baaf3c71cd8300d7a988962
Author: zilongshanren guanghui8827@126.com
Date:   Mon Feb 22 11:30:35 2016 +0800

```
add toggle native editbox logic
```

commit 2058f73ab82c1aa28c2ccf36046a727477a4c519
Merge: 744d8ad 595d744
Author: zilongshanren guanghui8827@126.com
Date:   Mon Feb 22 10:48:43 2016 +0800

```
Merge remote-tracking branch 'fireball/master'
```

commit 744d8ad93d6b8bc322173c828be954b9f2834bbb
Author: zilongshanren guanghui8827@126.com
Date:   Fri Feb 19 13:37:34 2016 +0800

```
remove resize and add vertical scrollbar
```

### CODE REVIEW

**Comment by zilongshanren** [comment]
fixes cocos-creator/fireball#1933
fixes cocos-creator/fireball#1932

**Comment by zilongshanren** [comment]
@jareguo @pandamicro  新的PR

**Comment by zilongshanren** [comment]
测试例修改：cocos-creator/example-cases#64

**Comment by jareguo** [comment]
谢邀，我没问题

**Comment by zilongshanren** [comment]
@jareguo 求合并？？

**Pull request merged**
