### PR TITLE
fix download url request not encode space

### PR DESCRIPTION
**Pull request by novain1102**
Re: #https://github.com/cocos/3d-tasks/issues/7874

### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by PatriceJiang** [comment]
Should we implement `url_encode` ?

**Comment by minggo** [comment]
As discussed, may let developers encode the url if needed.

**Comment by novain1102** [comment]
> Should we implement `url_encode` ?

In native, the encoding methods in different platforms are not consistent. Eg, Windows needs locate some last of char like `/`to substr the string and then call `curl_easy_escape()`, which will affect the performance when deal with amount of requests, And another potential problem is that if it is a `POST` request, which may be very long and cotains special char after `/`, the position of this substr is not accurate. so I think developer do the encoding if needed is a better approach.

**Comment by minggo** [comment]
It is better to provide a function to encode the string.

**Comment by novain1102** [comment]
> It is better to provide a function to encode the string.

We can't predict the url request pass in from the user. Eg:it may be an http resource request(in this case we can find last of '/' to encode) or a very long POST request with special characters (in this case, user must locate and encode the POST parameters separately, otherwise an error will occur). So different urls need to encode in different way, and the engine cannot encode uniformly. The better approach is to let the user do encoding before passing in.

**Comment by minggo** [comment]
What i mean is to encode the space, as did in the PR.

**Review by minggo — APPROVED** [review]

**Pull request merged**
