### PR TITLE
Improve pause & resume logic

### PR DESCRIPTION
**Pull request by pandamicro**
Re: cocos-creator/fireball#3528

Changes proposed in this pull request:
- Improve pause & resume logic

> Makes sure these boxes are checked before submitting your PR - thank you!
> - [x] If your pull request has gone "stale", you should **rebase** your work on top of the latest version of the upstream branch.
> - [x] If your commit history is full of small, unimportant commits (such as "fix pep8" or "update tests"), **squash** your commits down to a few, or one, discreet changesets before submitting a pull request.
> - To official teams:
>   - [x] Check that your javascript is following our [style guide](https://github.com/cocos-creator/fireball/blob/dev/.github/CONTRIBUTING.md) and end files with a newline
>   - [x] Document new code with comments in source code based on [API Docs](https://github.com/cocos-creator/fireball#api-docs)

@cocos-creator/engine-admins

### CODE REVIEW

**Comment by jareguo** [comment]
jsb 是不是也要改一下

**Comment by pandamicro** [comment]
@jareguo 又找不到 async 库了

**Comment by pandamicro** [comment]
> jsb 是不是也要改一下

不用，兼容的

**Comment by jareguo** [comment]
@VisualSJ 看看

**Pull request merged**
