### PR TITLE
fix sys.os/sys.isMobile on minigame platform

### PR DESCRIPTION
**Pull request by WenhaiLin**
Re: #

### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by minggo** [comment]
@qiuguohua if this PR is valuable, we should sync to v3.8.3.

**Review by dumganhar — APPROVED** [review]

**Review by qiuguohua — APPROVED** [review]

**Comment by dumganhar** [comment]
@qiuguohua Currently, develop branch is not active, I think we need to cherry-pick this PR to 3.8.4 branch.

**Comment by qiuguohua** [comment]
OK

**Comment by WenhaiLin** [comment]
满一年了，吐槽下

**Pull request closed without merging**
