### PR TITLE
[V1.2] Added global fog

### PR DESCRIPTION
**Pull request by GengineJS**
Changes:
 * Added global fog

### CODE REVIEW

**Comment by GengineJS** [comment]
Replace the submitted branch with 3d-v1.1.1 https://github.com/cocos-creator/engine/pull/6439

**Comment by GengineJS** [comment]
https://github.com/cocos-creator/3d-tasks/issues/3218

**Comment by pandamicro** [comment]
需要在 3d 分支下重新生成一下 effects

**Review by YunHsiao — APPROVED** [review]
好像还带了点其他 pr 的东西，需要整理一下

**Comment by GengineJS** [comment]
https://github.com/cocos-creator/engine/pull/6675

**Pull request closed without merging**
