### PR TITLE
do not use align malloc

### PR DESCRIPTION
**Pull request by minggo**
c++17 supports create an aligned struct

### CODE REVIEW

**Review by star-e — APPROVED** [review]

**Review by PatriceJiang — APPROVED** [review]

**Comment by yiwenxue** [comment]
https://github.com/cocos/cocos-engine/blob/eaddf1dab7cdef8a24eca7cc85d01267abd01a82/native/cocos/renderer/gfx-agent/CommandBufferAgent.cpp#L95
https://github.com/cocos/cocos-engine/blob/d1e141990bd28bab86597589c1c2672e057e265c/native/cocos/renderer/gfx-agent/DeviceAgent.cpp#L306-L307
they should be adapted as well?

**Review by yiwenxue — APPROVED** [review]

**Comment by star-e** [comment]
Is c++17 aligned new supported on old iOS and Android？

**Comment by PatriceJiang** [comment]
These two lines 
image
should be revert according to origin commit
image

**Comment by minggo** [comment]
> Is c++17 aligned new supported on old iOS and Android？

Yep, i tested with iPhone 6s with iOS 11.2. And c++17 always works on Android.

**Pull request merged**
