### PR TITLE
Spotlight interface description change for v3.5.1

### PR DESCRIPTION
**Pull request by troublemaker52025**
Re: #

Changelog:
 *

### CODE REVIEW

**Comment by troublemaker52025** [comment]
* https://github.com/cocos/3d-tasks/issues/12184

**Review by minggo — APPROVED** [review]

**Comment by pandamicro** [comment]
It does't seem appropriate, if aspect for the shadow projection matrix is useful and user need to control it, then we should expose it at component level, not removing it

**Comment by jk20012001** [comment]
Aspect is an attribute of camera, not light source. It use for fit render target x/y. Shadowmap width always equals to height, so dirlight / spotlight / pointlight should use 1.0 in shadow project matrix.
If you modify shadowmap aspect, lighting model also needs to be modified, but we don't have any aspect-related calculations in lighting.
UE4 and Unity don't have this attribute at all. So user don't need to obtain or modify this value, I suggest that remove it from light component.

**Comment by pandamicro** [comment]
Ok, got it, @troublemaker52025 please resolve conflicts

**Comment by troublemaker52025** [comment]
@cocos-robot run test cases

**Pull request merged**
