### PR TITLE
Remove unused code: defineOwnProperty("__native_ptr__",...)

### PR DESCRIPTION
**Pull request by dumganhar**
Re: #

Changelog:
 *

### CODE REVIEW

**Comment by minggo** [comment]
Is there a way to distinguish native binding object or pure javascript object?

**Review by PatriceJiang — APPROVED** [review]

**Comment by dumganhar** [comment]
> Is there a way to distinguish native binding object or pure javascript object?
What kinds of situations that need to distinguish? 
If we really need to distinguish, we should do it in another way in class registration. For example, do it in register class method. Define property in runtime dynamically will make code run slower.
```c++
bool js_register_ccc(se::Object* obj) // NOLINT(readability-identifier-naming)
{
    auto* cls = se::Class::create("ccc", obj, nullptr, _SE(js_ccc_constructor));
    ......
    cls->defineProperty("nativePtr", _SE(js_ccc_get_nativePtr), nullptr); // Add this line 
    cls->defineStaticProperty("isJSBClass", _SE(js_ccc_static_get_isJSBClass), nullptr);// Add this line 
    cls->install();
    JSBClassType::registerClass<cc::IPassInfoFull>(cls);

    __jsb_cc_ccc_proto = cls->getProto();
    __jsb_cc_ccc_class = cls;

    se::ScriptEngine::getInstance()->clearException();
    return true;
}
```

**Comment by minggo** [comment]
> What kinds of situations that need to distinguish?

As some classes are implemented both in TS and c++, sometimes we want to make sure if TS related codes are deleted correctly, then need it.

**Comment by minggo** [comment]
This PR looks good to me, just need another way to distinguish if an object is a pure TS object or a bound object in debug mode.

**Review by minggo — APPROVED** [review]

**Comment by dumganhar** [comment]
> This PR looks good to me, just need another way to distinguish if an object is a pure TS object or a bound object in debug mode.

Fixed at https://github.com/cocos/cocos-engine/pull/10993

**Pull request merged**
