### PR TITLE
[V1.1.1] Added global fog

### PR DESCRIPTION
**Pull request by GengineJS**
Re: cocos-creator/2d-tasks#

Changes:
 * Added global fog

-->

### CODE REVIEW

**Comment by GengineJS** [comment]
Editor shader pr  https://github.com/cocos-creator/editor-3d/pull/3287

**Review by YunHsiao — APPROVED** [review]

**Comment by GengineJS** [comment]
@MSoft1115  @gameall3d  @troublemaker52025 麻烦审核下

**Review by troublemaker52025 — APPROVED** [review]

**Comment by YunHsiao** [comment]
ci 挂了，应该是 cc 下加新东西了，不用再写 cc.xxx = xxx 了

**Review by gameall3d — APPROVED** [review]
LGTM

**Review by MSoft1115 — COMMENTED** [review]
没问题，不过global buffer的设计最好改成动态的

**Comment by GengineJS** [comment]
Replace the submitted branch with 3d-v1.1.1

**Pull request closed without merging**
