### PR TITLE
[v3.6.1-shader] add deferred shader compiling

### PR DESCRIPTION
**Pull request by star-e**
Deferred shader compiling. Only compile shader when actually used.

### Changelog

* refactored all shader backends

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by star-e** [comment]
@cocos-robot run test cases

**Comment by suqionglian** [comment]
@cocos-robot run test cases

**Comment by star-e** [comment]
@cocos-robot run test cases

**Review by minggo — APPROVED** [review]

**Comment by hana-alice** [comment]
In my understanding this delay the shader initialization from init to first time get the gpuObject, it decreases peak compilation time. @bluesky013 once he told me maybe all gfx object initialization can be done as a task(by TBB/taskflow). Do we have any plan on send these initializations to a task? if we do, does this pr has any harm on how we will implement the `task`?

**Comment by star-e** [comment]
I can add a macro to disable deferred shader compiling.

The purpose of this pr is to reduce the number of shaders that need compiling.
I don't think this is a good way to solve this problem, but it is the only practical way I can think of.
Actually, it's user's responsibility to specify the subset of shader need compiling and we should provide this feature in the future.
Deferred shader compiling should be turned off, when shader subset-compiling is supported.

We should also provide batch/multi-threaded/async shader compiling in the future.

**Review by hana-alice — APPROVED** [review]

**Comment by star-e** [comment]
相关issue  https://github.com/cocos/3d-tasks/issues/13642

**Comment by star-e** [comment]
Related issue in cocos-engine  https://github.com/cocos/cocos-engine/issues/12396

**Pull request merged**
